### ISSUE TITLE
Unable to execute setup.py on EC2

### ISSUE THREAD

**Issue by Shadowh0st** [CheckPointSW/Cuckoo-AWS#10]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

**Comment by chkp-orank** [comment]
Hi @Shadowh0st,

Did you follow the procedure as it appears at our README.md?

Did you try to run "python stuff/monitor.py" before executing "python setup.py sdist develop"?

**Comment by chkp-mostafaw** [comment]
Next week we will publish a new installation document.

For now, we are closing this issue, if the error reoccurs then please open a new issue.
