### ISSUE TITLE
Network Analysis is empty

### ISSUE THREAD

**Issue by sfoxdev** [CheckPointSW/Cuckoo-AWS#12]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at: No errors in all log files

New installation on Ubuntu 18.04 LTS instance, network interface `ens5` configured in `aws.conf`
```
[aws]
...
# Default network interface.
interface = ens5
...
[autoscale]
...
# Default network interface.
interface = ens5
...
```
and in `routing.conf`
```
[routing]
route = none
internet = ens5
rt_table = main
auto_rt = yes
drop = yes
[inetsim]
enabled = yes
server = 172.32.5.11
[tor]
enabled = yes
dnsport = 5353
proxyport = 9040
[vpn]
enabled = no
...
```
Router process is running without errors in log.

On submit selecting any type of network Internet/Inetsim/Tor doesn't make any effect.
After file analysis finished `Network Analysis` section is empty.

**Comment by freis** [comment]
Having similar problem, my pcap analysis is close to empty. Found any way to solve this?

**Comment by chkp-orank** [comment]
Hi @freis and @sfoxdev.

By AWS default, the traffic does not pass via the Nest.
To force traffic via the Nest, we needed to change the route table of the guest's image.

Make a .bat script that will run at startup.
The script should contain 2 lines:
1.  route add 0.0.0.0/0 <Nest IP>
2.  route delete 0.0.0.0/0 <AWS subnet GW>

Let me know if that solves your issues

**Comment by chkp-mostafaw** [comment]
Next week we will publish a new installation document (including detailed instructions of how to set these routing via the Nest machine).

For now, we are closing this issue, if the error re-occurs then please open a new issue.

**Comment by freis** [comment]
Added a bat file to the startup with those two lines but nothing changed.

**Comment by chkp-orank** [comment]
@freis,

what is your Nest IP?

On your guest please run 'route print -4' and attach the output to your next reply.
