### ISSUE TITLE
Update README.md with full step-by-step installation guide

### ISSUE THREAD

**Issue by sfoxdev** [CheckPointSW/Cuckoo-AWS#13]
For last week I tried different installations of Cuckoo-AWS on different instances without 100% success, all time I'm fighting with different errors and issues.
Instances:
- t2.medium - FAILED - low CPU, low RAM memory
- t2.large - FAILED - low CPU, low RAM memory
- t2.xlarge - FAILED - low CPU, RAM memory OK
- m5.xlarge - OK - all 4 CPU works on 100%, RAM memory works on 50-70%

Looks that `m5.2xlarge` should be OK, but not sure, didn't try yet.

Read here in Issues that you running it on Ubuntu 16.04 LTS, but it's not true. I made few tries to install it on Ubuntu 16.04 LTS from scratch without success. Faced with a lot of dependencies errors when running `python setup.py sdist develop` and this only on beginning of setup, who knows what errors could be found after. Here I gave up and moved to Ubuntu 18.04 LTS.

Using Ubuntu 18.04 LTS was more successful, but unfortunately not all functionality working as expected.

@chkp-adamr (Adam Richter) and @chkp-mostafaw (Mostafa Wattad) you made great improvement to run Cuckoo in AWS instances, but it doesn't have any sense without step-by-step documentation how to install it. I believe that your version of Cuckoo-AWS is running great somewhere on your environment, but after reading all Issues here I didn't see anyone who run it successfully by him-self.

Please update README.md file with complete step-by-step guide how to setup Cuckoo-AWS with basic modules and required software (I mean Cuckoo Sandbox + MongoDB + Postgres + Guacd + Java + Elasticsearch + Yara + SSDeep + Volatility + TCPDump + Teserract + PDF + MitMproxy + iproute2 + Tor + Suricata + Snort + Moloch + InetSim + UWSGI + Nginx and others, if I something missed)

**Comment by chkp-mostafaw** [comment]
Hi,
Thank you for the feedback, the deployment of this solution has a lot dependencies.
We will publish a step-by-step documentation very soon, in addition we will publish an easy deployment method to make it easier for adaption.

**Comment by freis** [comment]
Any update on when more documentation will be available?

Regards.

**Comment by chkp-mostafaw** [comment]
Hi,
We will provide more documentation and a deployment method next month.

**Comment by riparino** [comment]
Will a metal I stance with 18.04 work? It look like if you just install the standard cuckoo dependencies and flip over to this guide to complete the setup it should be ok. A guide would be fantastic though.

**Comment by chkp-orank** [comment]
@riparino,

Yes, you can install some hypervisor system(vmware, virtualbox..) on i3.metal and use the standard cuckoo repository on AWS.

The solution here does not require any hypervisor installation.
Moreover, it utilizes cloud features like scalability and elasticity and let cuckoo scale-up and down as needed without users interference which is crucial for application that runs in the cloud.

You are welcome to read more about it on my blog post
https://research.checkpoint.com/cuckoo-system-on-aws/

**Comment by chkp-mostafaw** [comment]
Next week we will publish a new installation document.

For now, we are closing this issue.

**Comment by freis** [comment]
Any update on this installation document?

**Comment by chkp-mostafaw** [comment]
Hi,
Sorry for the delay, We are still working on the document.
We will publish it once Done

**Comment by freis** [comment]
No updates on this part?

**Comment by ashesbelow** [comment]
Also looking for update on document.

**Comment by e0267744** [comment]
Dear team, 

Is there any update with regard to the document please?
