### ISSUE TITLE
Installing CuckooAWS on AmazonLinux - Successful but config error

### ISSUE THREAD

**Issue by ashesbelow** [CheckPointSW/Cuckoo-AWS#16]
I was able to successfully install CuckooAWS on AmazonLinux using the following commands, in this order:

===========

sudo yum update
sudo yum install python2 python2-pip
sudo pip2 install -U pip setuptools
sudo yum install libjpeg-turbo-devel zlib-devel gcc openssl-devel libffi-devel python-devel
sudo yum install git
git clone https://github.com/CheckPointSW/Cuckoo-AWS
sudo pip2 install boto3
cd Cuckoo-AWS/
sudo pip2 install alembic==0.8.8 androguard==3.0.1 beautifulsoup4==4.5.3 chardet==2.3.0 click==6.6 cryptography==2.3 django==1.8.4 django_extensions==1.6.7 dpkt==1.8.7 egghatch==0.2.3 elasticsearch==5.3.0 flask==0.12.2 flask-sqlalchemy==2.1 httpreplay==0.2.2 jinja2==2.9.6 jsbeautifier==1.6.2 oletools==0.51 peepdf==0.4.2 pefile2==1.2.11 pillow==3.2 pyelftools==0.24 pyguacamole==0.6 pymisp==2.4.54 pymongo==3.0.3 python-dateutil==2.4.2 python-magic==0.4.12 requests[security]==2.13.0 roach==0.1.2 sflock==0.3.5 sqlalchemy==1.0.8 unicorn==1.0.1 wakeonlan==0.2.2 yara-python==3.6.3

sudo pip2 install six==1.10.0
sudo pip2 install cryptography==2.8

python stuff/monitor.py
sudo python setup.py sdist develop

cuckoo -d

=============

However, after resolving several config errors, there is one I do not understand where the issue is. After running "cuckoo" after changing the configs per instructions, I end with the error (instance ID changed for security):

2019-11-18 17:27:26,487 [cuckoo] CRITICAL: CuckooConfigurationError: Option i-05f07711cxxxxxxx is not found in configuration

The following is the configuration in my aws.conf file:

\# Specify a comma-separated list of available machines to be used.
\# Each machine will be represented by the instance-id (for example, i-05f07711c635f817f).
\# For each specified instance-id you have to define a dedicated section containing the details
\# on the respective machine. (E.g. i-05f07711c635f817f,i-04d465547cba1af5e)
\# For better performance, it is recommended to leave this empty and set autoscale = yes.
machines =  i-05f07711cxxxxxxx

I do not need/want to autoscale and only have one Windows sandbox machine. Why am I getting this error?

**Comment by chkp-mostafaw** [comment]
Hi,
Did you add a dedicated section for the instance ID in the config file as the documentation said?

**Comment by ashesbelow** [comment]
I think I see what you are referring to:

# For each specified instance-id you have to define a dedicated section containing the details
# on the respective machine. (E.g. i-05f07711c635f817f,i-04d465547cba1af5e)

but the "e.g." only shows a comma separated list of instance IDs. Since I only have one instance, I used "machines = i-05f07711cxxxxxxx" as shown in my OP. The comment in the aws.conf doesnt specify what need to be in that "dedicated section." Is there a document that shows me what needs to be in that section?

**Comment by ashesbelow** [comment]
Ok I finally saw the section you were talking about but the documentation is very unclear. For others researching this, the section Mostafa is referring to is towards the bottom starting with the below:

[i-0cf3d28bXXXXXX]
# Specify the label name.
# Label would be the instance-id of the current machine as specified in your AWS account.
label = i-0cf3d28bXXXXXX 

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail.
ip = 10.171.XXX.XX

# Specify the snapshot-id to use. it is used when creating a new volume when restoring a machine.
# You should create a snapshot from the guest machine.
snapshot = snap-08200xxxxx

Remember to change the instance-id in the brackets also.
