### ISSUE TITLE
RunInstances operation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by siarkszy** [CheckPointSW/Cuckoo-AWS#21]
Hello, I tried to run Cuckoo-AWS with configuration which should be able to create instances automatically:

```conf
machines = 
autoscale = yes
```

And policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:RebootInstances",
                "ec2:RunInstances",
                "ec2:TerminateInstances"
            ],
            "Resource": [
                "arn:aws:ec2:eu-north-1:588503228815:instance/*"
            ]
        }
    ]
}
```

But unfortunately mu cuckoo instance is finishing with error message:

```
ClientError: An error occurred (UnauthorizedOperation) when calling the RunInstances operation: You are not authorized to perform this operation. Encoded authorization failure message:
```

Can you tell me what permissions in AWS are required? (or what should I do to run it)
Btw it would be nice to have information about this in some sort of Wiki / Readme.

**Comment by chkp-mostafaw** [comment]
As I see in your IAM role, you have all permessions in eu-north-1 region.
Are you sure this the same region you configured in aws.conf file ? (region_name = {{ aws.aws.region_name }} section)
@chkp-orank please add this info to the readme
