### ISSUE TITLE
Full step-by-step installation guide

### ISSUE THREAD

**Issue by e0267744** [CheckPointSW/Cuckoo-AWS#22]
> Update README.md with full step-by-step installation guide  #13

Referring to this closed issue #13 , is this still something that we can look forward to? Thanks!

**Comment by chkp-mostafaw** [comment]
We are going to change the deployment method of the cuckoo on AWS
Therefore, the installation guide will be available once it's finished.

**Comment by harshn1904** [comment]
Hi guys!
how did you setup cuckoo on aws? can you please guide me?
thank you!!
