### ISSUE TITLE
updated install guide 

### ISSUE THREAD

**Issue by siftuser** [CheckPointSW/Cuckoo-AWS#24]
Hi @chkp-mostafaw! 

Is there any update on updated install guide as suggested in https://github.com/CheckPointSW/Cuckoo-AWS/issues/22. Thanks!

**Comment by PuneethRaya** [comment]
Can you please let us know, When can we expect this installation guide?

**Comment by chkp-mostafaw** [comment]
Hi,
We will have the installation guide on February.

**Comment by chkp-mostafaw** [comment]
We added cloudformation stack: cuckoo-aws-cloudformation.yaml, All you need to do is running it and you will receive an EC2 instance with all the requirements installed in it
