### ISSUE TITLE
Issue installing Cuckoo on AW

### ISSUE THREAD

**Issue by ants9520** [CheckPointSW/Cuckoo-AWS#31]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: Hi, Whilst trying to install Cuckoo and following guidelines, i get stuck when running "python setup.py sdist develop"
https://github.com/CheckPointSW/Cuckoo-AWS  

##### The log, error, files etc can be found at:

Installed /home/ubuntu/Cuckoo-AWS
Processing dependencies for Cuckoo==2.0.6.2
Searching for idna>=2.0.0
Reading https://pypi.python.org/simple/idna/
Best match: idna 3.1
Downloading https://files.pythonhosted.org/packages/9f/24/1444ee2c9aee531783c031072a273182109c6800320868ab87675d147a05/idna-3.1.tar.gz#sha256=c5b02147e01ea9920e6b0a3f1f7bb833612d507592c837a6c49552768f4054e1
Processing idna-3.1.tar.gz
Writing /tmp/easy_install-5xmBRY/idna-3.1/setup.cfg
Running idna-3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5xmBRY/idna-3.1/egg-dist-tmp-q8j9rR

The following error has occurred while trying to install Cuckoo!

Traceback (most recent call last):
  File "setup.py", line 129, in do_setup
    setuptools.setup(**kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Setup script exited with Sorry, Python 3.4 or newer required

Make sure that you've installed all requirements for Cuckoo
to be installed properly! Please refer to our documentation:
https://cuckoo.sh/docs/installation/host/requirements.html

Once you have triple checked that all dependencies have been
installed but Cuckoo still fails, please feel free to reach
out to us on IRC / email / Github!

  But don't forget to check out our documentation for full
  installation steps. You might also want to check our FAQ.
(venv) ubuntu@ip-x.x.x.x:~/Cuckoo-AWS$ python -V
Python 3.5.2
(venv) ubuntu@ip-x.x.x.x:~/Cuckoo-AWS$

**Comment by chkp-mostafaw** [comment]
Hi,
We added cloudformation stack:  cuckoo-aws-cloudformation.yaml, run it and you will receive an EC2 instance with all the requirements installed in it

**Comment by harshn1904** [comment]
how to run cuckoo-aws-cloudformation.yaml?

**Comment by harshn1904** [comment]
Hi guys!
how did you setup cuckoo on aws? can you please guide me?
thank you!!
