### ISSUE TITLE
What is the recommended Version for this deployment in AWS? What linux flavor?

### ISSUE THREAD

**Issue by securecars66** [CheckPointSW/Cuckoo-AWS#7]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
wondering what version should I use in AWS? I've been having issues with various flavors. I was wondering what version checkpoint recommends as i don't see it in the instructions or requirements. 
##### My Cuckoo version and operating system are:
N/A
##### This can be reproduced by:
N/A
##### The log, error, files etc can be found at:
N/A

**Comment by chkp-orank** [comment]
Hello @securecars66.

We run it successfully on Ubuntu 16.04.
I believe that the minimum requirements for the Nest server is type t2.large, and t2.medium for each guests.

**Comment by chkp-orank** [comment]
please share with us the issues that you had.

**Comment by securecars66** [comment]
I'll try on 16.04. I did it on 18.04 I will post my updates soon.

**Comment by Shadowh0st** [comment]
Hey @securecars66 

Can you please share the detailed installation. As after cloning the repository on my AWS Ubuntu 18.04 VM, i am unable to proceed with further steps. I tried running "setup.py" but it is giving multiple issues. Is there any prerequisite steps i need to do, Kindly tell?

**Comment by chkp-orank** [comment]
@securecars66,

you should set your Ubuntu private IP in the followings fields:
1.  resultserver_ip  at aws.conf
2.  ip (under [resultserver] section) at cuckoo.conf

Can you please provide the exact error after it breaks in the cuckoo.conf?

**Comment by chkp-mostafaw** [comment]
Next week we will publish a new installation document (including the missing packages).

For now, we are closing this issue, if the error re-occurs then please open a new issue.
