### ISSUE TITLE
cuckoo unable to bind resultserver

### ISSUE THREAD

**Issue by securecars66** [CheckPointSW/Cuckoo-AWS#8]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
unable to start cuckoo because of error
##### My Cuckoo version and operating system are:
Distributor ID:Ubuntu
Description:Ubuntu 18.04.2 LTS
Release:18.04
Codename:bionic
##### This can be reproduced by:
trying to start cuckoo in AWS on ubuntu after following these instructions

##### The log, error, files etc can be found at:
ERROR I GET:
CuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:2042 [Errno 99] Cannot a
ssign requested address. This usually happens when you start Cuckoo without bringing up the virtual interface associated with the Re
sultServer IP address. Please refer to https://cuckoo.sh/docs/faq/#troubles-problem for more information.

Please help

**Comment by chkp-orank** [comment]
Hello @securecars66 .

please check ".cuckoo/conf/cuckoo.conf" file
make sure that the IP(under [resultserver]) has the private IP of your machine.

for more information please read the README.md file

**Comment by securecars66** [comment]
Thanks. I did that and it appears it still doesn't start correctly. 
CuckooCriticalError: Unable to bind ResultServer on 192.168.56.1:2042 [Errno 99] Cannot assign requested address. T
his usually happens when you start Cuckoo without bringing up the virtual interface associated with the ResultServer IP address. Please refer to https://cucko
o.sh/docs/faq/#troubles-problem for more information.

The IP 192.168.56.1 is not the IP. 

![image](https://user-images.githubusercontent.com/48285561/55746267-49be7400-5a07-11e9-90e6-6db24a8f3b2c.png)

**Comment by chkp-orank** [comment]
I traced that exact error location at the code(cuckoo\core\resultserver.py).

It is printing your error among with the IP as configured in cuckoo.conf.
Please make sure that you changed that at cuckoo.conf (as 192.168.56.1 is the default IP)

If there's still an error, then try searching the string '192.168.56.1' in cuckoo's directory so we will know where this configuration is coming from.

**Comment by chkp-mostafaw** [comment]
We are closing this issue, if the error reoccurs then please open a new issue.

**Comment by harshn1904** [comment]
Hi guys!
how did you setup cuckoo on aws? can you please guide me?
thank you!!
